# Generated by Django 5.2.15 on 2026-07-20 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_messagereaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("IDLE", "Idle"),
                            ("DND", "Do Not Disturb"),
                            ("INVISIBLE", "Invisible"),
                        ],
                        default="ONLINE",
                        max_length=20,
                    ),
                ),
                ("custom_status", models.CharField(blank=True, max_length=128)),
                ("custom_status_emoji", models.CharField(blank=True, max_length=32)),
                (
                    "custom_status_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_presence",
            },
        ),
    ]
