# Generated by Django 5.2.15 on 2026-07-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_userpresence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpresence",
            name="status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("idle", "Idle"),
                    ("dnd", "Do Not Disturb"),
                    ("invisible", "Invisible"),
                ],
                default="online",
                max_length=20,
            ),
        ),
    ]
