# Generated by Django 5.2.15 on 2026-07-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_userpresence_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
