
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'core.exceptions.custom_api_exception_handler',
}
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

CLIENT_URI = os.getenv("CLIENT_URI", "http://localhost:3000")

if DEBUG:
    ALLOWED_HOSTS = ["*"]

    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

    CORS_ALLOWED_ORIGINS = [
        CLIENT_URI,
    ]
    CORS_ALLOW_CREDENTIALS = True


GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")


# Application definition

INSTALLED_APPS = [
    # Daphne must come first so its runserver replaces Django's WSGI one
    # (enables ASGI / WebSocket support in development).
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "corsheaders",
    "rest_framework",
    "campuses",
    "users",
    "posts",
    "comments",
    "common",
    "chat",
]

# settings.py

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"

# Channels / real-time
# Uses Redis when REDIS_URL is set (production / docker), otherwise falls back
# to the in-memory layer so the app runs with `runserver` in local dev without
# a Redis instance. The in-memory layer is single-process only (not for prod).
#
# If Redis is configured but temporarily unavailable, the chat consumer and
# realtime helpers now degrade gracefully instead of crashing the connection.
REDIS_URL = os.getenv("REDIS_URL", "")

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                # Use a dict host entry so redis-py connection kwargs can be passed.
                # Increase socket_timeout and enable retry_on_timeout so transient
                # delays don't immediately raise TimeoutError and drop websocket
                # connections. These values are conservative for a dev environment.
                "hosts": [
                    {
                        "address": REDIS_URL,
                        "socket_connect_timeout": 10,
                        "socket_timeout": 60,
                        "retry_on_timeout": True,
                    }
                ],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Production and containerized development use PostgreSQL. Local check/test runs
# should still work without a database host, so fall back to SQLite when no
# explicit Postgres host is configured.
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "")
RUNNING_TESTS = any(arg in {"test", "pytest"} for arg in sys.argv)

if POSTGRES_HOST and not RUNNING_TESTS:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": POSTGRES_HOST,
            "PORT": os.getenv("POSTGRES_PORT"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Rate limiting — protects the API from abuse / runaway clients.
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "40/min",
        "user": "400/min",
    },
}

# In DEBUG (local development) increase throttle limits to avoid accidental 429s
# from aggressive client-side polling or dev browsers. Keep production limits
# conservative.
if DEBUG:
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": "1000/min",
        "user": "5000/min",
    }

# Cache — backs real-time presence tracking, so it MUST be shared across
# processes/workers in production. When REDIS_URL is set we use Redis (the same
# instance that powers the channel layer); otherwise fall back to the
# single-process in-memory cache for local dev without Redis.
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 300,
            "KEY_PREFIX": "campus-connect",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "campus-connect-cache",
            "TIMEOUT": 300,
        }
    }

# Email / contact form
# Defaults to the console backend (prints to terminal) so the contact form works
# in dev without SMTP. For real delivery set EMAIL_BACKEND=smtp + the SMTP_* vars.
# CONTACT_EMAIL is the destination for Help messages — kept server-side only and
# NEVER exposed to the client (no mailto / no API field).
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL", "Campus Connect <no-reply@campusconnect.local>"
)
CONTACT_EMAIL = os.getenv("CONTACT_EMAIL", "")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media (user uploads — post images). Served by Django in development.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Allow larger multipart bodies for image uploads (10 MB).
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
