# Generated by Django 5.2.15 on 2026-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='campus',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='campus',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
