name: CampusConnect CI

on:
  push:
    branches:
      - main
      - develop
      - prasangeet
      - mayuri

  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync

      - name: Ruff
        run: uv run ruff check .

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
